### ISSUE TITLE
Duplicate message returned from query

### ISSUE THREAD

**Issue by maximeloizeau** [layerhq/layer-react#1] opened 2016-06-07 17:07 UTC
Hi,

First, thanks a lot guys for these web libraries ! Really useful and wll supported !

My issue:
I have a component wrapped by a `connectQuery({}, getQueries)` with this query:
```
QueryBuilder
      .messages()
      .forConversation(activeConversationId)
      .paginationWindow(messagePagination)
```

When I create a new message in this conversation, here is the changes I get:
**Before creation**: `["layer:///messages/34db70d7-3db1-40fc-85d2-24fa46c4794e"]`
**On creation**: 
```
[
"layer:///messages/34db70d7-3db1-40fc-85d2-24fa46c4794e",
"temp_layer:///messages/ee4d4c54-689a-4a65-b825-6fe340ef3757"
]
```
**A bit after, the message has been sync with the servers**:
```
[
"layer:///messages/34db70d7-3db1-40fc-85d2-24fa46c4794e",
"temp_layer:///messages/ee4d4c54-689a-4a65-b825-6fe340ef3757",
"layer:///messages/6c04e354-f118-4321-bd98-3f3384d5f89e"
]
```
**A bit after**:
```
[
"layer:///messages/34db70d7-3db1-40fc-85d2-24fa46c4794e",
"layer:///messages/6c04e354-f118-4321-bd98-3f3384d5f89e",
"layer:///messages/6c04e354-f118-4321-bd98-3f3384d5f89e"
]
```

The temporary message has been synchronized and its id has been replaced with the correct one. Except that it makes duplicate.

Can you replicate this ? I will investigate on it tomorrow more in details, in case that is my fault.

**Comment by nilgradisnik** [comment] 2016-06-09 21:26
Hey @maximeloizeau thanks for you feedback, I was not able to reproduce this. Which version of WebSDK are you using?

**Comment by maximeloizeau** [comment] 2016-06-10 09:27
I am now using 1.0.7. It doesn't always happen actually. I'm try to find the state when it happens (and this might an issue on my side then).

I'll keep you updated.

**Comment by nilgradisnik** [comment] 2016-08-03 00:52
Closing this. Re-open if the issue persist.

**Closed by nilgradisnik** 2016-08-03 00:52 UTC
